name: Generate 3D contribution graph

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A profile-3d-contrib
          if git commit -m "chore: update 3d contribution graph"; then
            git push
          fi
